spring.application.name=App


#DATABASE CONNECTION
spring.datasource.url=jdbc:mysql://localhost:3306/bookmovie
spring.datasource.username=root
spring.datasource.password=9635

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JWT
jwt.secret = aBJsjnd@$#dfkvnjnvndknvkj125cdnjbcjbsbjbjdbbhbjcv45NDNFJN
jwt.expiration = 3600000

